### ISSUE TITLE
Cannot install Threads

### ISSUE THREAD

**Issue by ghost** [ldelgado-serrano/mycofier#1]
Hi,

can't run because cannot install 'Threads'.

cpan[3]> install Threads;
Warning: Cannot install Threads;, don't know what it is.
Try the command

```
i /Threads;/
```

to find objects with matching identifiers.

MycofierClassificatorPERL.pl -infile filtered.fasta -outfile tax_myco.txt -numthreads 20
Can't locate Threads.pm in @INC (@INC contains: /home/theoa/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /home/theoa/perl5/lib/perl5/5.16.3 /home/theoa/perl5/lib/perl5/x86_64-linux-thread-multi /home/theoa/perl5/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /home/theoa/bin/t-coffee/perl/lib/perl5/x86_64-linux-thread-multi /home/theoa/bin/t-coffee/perl/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/theoa/bin/mycofier/PERL/MycofierClassificatorPERL.pl line 13.
BEGIN failed--compilation aborted at /home/theoa/bin/mycofier/PERL/MycofierClassificatorPERL.pl line 13.

**Comment by ldelgado-serrano** [comment]
Hi, 
You should do in CPAN the follow command:
install Thread::Queue

**Comment by ghost** [comment]
Hi,

get this error now:

MycofierClassificatorPERL.pl -infile filtered.fasta -outfile tax_myco.txt -numthreads 20
Can't locate Threads.pm in @INC (@INC contains: /home/theoa/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi / .... <very long path list>
BEGIN failed--compilation aborted at /home/theoa/bin/mycofier/PERL/MycofierClassificatorPERL.pl line 13.

Thanks,

Theo

Dr Theo Allnutt
Bioinformatics Research Fellow
School of Medicine, Faculty of Health
Waurn Ponds Campus
0352479571

[cid:image001.png@01D21E29.39E35D60]

Deakin University
Locked Bag 20000, Geelong, VIC 3220
+61 3 524 79571
theo.allnutt@deakin.edu.aumailto:theo.allnutt@deakin.edu.au
www.deakin.edu.auhttp://www.deakin.edu.au/
Deakin University CRICOS Provider Code 00113B

Important Notice: The contents of this email are intended solely for the named addressee and are confidential; any unauthorised use, reproduction or storage of the contents is expressly prohibited. If you have received this email in error, please delete it and any attachments immediately and advise the sender by return email or telephone.

Deakin University does not warrant that this email and any attachments are error or virus free.

**Comment by ldelgado-serrano** [comment]
Hi, 
Sorry for the delay in replying. There was an error in the code. We will upload the code but in the meanwhile you could comment the code line "use threads" as:
"# use threads"
